### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by SalahAdDin** [thebuilder/meta-weather-proxy#6]
Basically, any time i try to get data i get:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.metaweather.com/api/location/search/?query=madrid. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`.

I'm trying to make it works with **axios**:
```
const BASE_URL = 'https://meta-weather.vercel.app/api/location/';
const axiosConfig: AxiosRequestConfig = {
  baseURL: BASE_URL,
};
const client: AxiosInstance = axios.create(axiosConfig);

const getCityByName = async (name: string): Promise<City> => {
  const { data } = await client.get<City>('search', {
    params: { query: name },
  });
  return data;
};

const getForecastWeatherByCity = async (cityID: number): Promise<Weather> => {
  const { data } = await client.get<Weather>(`${cityID}`);
  return data;
};

export { getCityByName, getForecastWeatherByCity };

```

What's the problem?

**Comment by thebuilder** [comment]
I should close this project. Hasn't been updated in 3 years now.
